-- You can use this file to load seed data into the database using SQL statements


INSERT INTO SOCIO(NOMBRE,APELLIDO,DNI,EMAIL) VALUES ('CAMILA','LONDERO','42441672','CAMLLON@HOTMAIL.COM');
INSERT INTO PELICULA(TITULO,SINOPSIS,ANIO,GENERO) VALUES ('TITANIC','UNA PELI',1820,0);
INSERT INTO PELICULA(TITULO,SINOPSIS,ANIO,GENERO) VALUES ('iron man','UNA PELI', 2014,0);
INSERT INTO ALQUILER(PELICULA_ID,SOCIO_ID,FECHA_ALQUILER) VALUES (1,1,'2020-10-10');